name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to deploy blog.
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true # Checkout private submodules(themes or something else).
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.1.0
      with:
        node-version: v18.16.0
    - name: Install dependencies
      run: npm install  # 安装项目依赖

    - name: Build Hexo
      run: npm run build  # 构建 Hexo 项目       
    
    - name: Deploy  # 步骤名称
      env:  # 设置环境变量
        GH_TOKEN: ${{ secrets.GH_TOKEN }}  # 使用 GitHub Secrets 存储的 GB_TOKEN
      run: |  # 执行多个命令
        git config --global user.name "2417357623"  # 设置 Git 全局用户名
        git config --global user.email "2417357623@qq.com"  # 设置 Git 全局用户邮箱
        npm run deploy  # 执行 npm run deploy 来部署 Hexo 博客

       
      
